#!/bin/bash
# E2E Testing Script for AMI-SYSTEM Phase 1 MVP
# Purpose: Manual walkthrough of complete expedient flow
# Date: 2026-01-22
# Estimated Time: 15-20 minutes

set -e

echo "================================================"
echo "AMI-SYSTEM Phase 1 E2E Test - Manual Walkthrough"
echo "================================================"
echo ""
echo "This script guides you through the complete E2E flow:"
echo "1. Create Expedient (patient medical file)"
echo "2. Add Medical Exam (vitals)"
echo "3. Upload Study (PDF/Image)"
echo "4. Validate Expedient"
echo "5. View Certificate Report"
echo ""
echo "Prerequisites:"
echo "- Local server running: pnpm dev"
echo "- Chrome/Firefox browser with Insomnia or Postman"
echo "- Sample PDF file (for upload test)"
echo ""
read -p "Press Enter to continue..."

# ============================================================================
# PHASE 1: CREATE EXPEDIENT
# ============================================================================
echo ""
echo "---"
echo "PHASE 1: CREATE EXPEDIENT"
echo "---"
echo ""
echo "1. Open browser and navigate to: http://localhost:3000/admin/expedientes"
echo ""
echo "2. Click 'Nueva Expediente' button"
echo ""
echo "3. Fill in form:"
echo "   - Patient Name: 'Juan García Pérez'"
echo "   - Date of Birth: '1985-06-15'"
echo "   - Clinic: Select from dropdown (e.g., 'Clínica Central')"
echo ""
echo "4. Click 'Crear' button"
echo ""
echo "Expected Result:"
echo "   ✓ Form submits successfully"
echo "   ✓ New expedient appears in list"
echo "   ✓ Expedient ID generated (e.g., cuid string)"
echo "   ✓ Status shows 'PENDIENTE'"
echo ""
read -p "Completed? Press Enter to continue..."

# ============================================================================
# PHASE 2: ADD MEDICAL EXAM
# ============================================================================
echo ""
echo "---"
echo "PHASE 2: ADD MEDICAL EXAM"
echo "---"
echo ""
echo "1. Click on the newly created expedient to open detail view"
echo ""
echo "2. Find 'Medical Exam' section and click 'Agregar Examen'"
echo ""
echo "3. Fill vitals form:"
echo "   - Blood Pressure: '120/80'"
echo "   - Heart Rate: '72'"
echo "   - Temperature: '37.0°C'"
echo "   - Respiratory Rate: '16'"
echo ""
echo "4. Click 'Guardar Examen' button"
echo ""
echo "Expected Result:"
echo "   ✓ Vitals saved to ValidationTask.studies"
echo "   ✓ Exam appears in expedient detail"
echo "   ✓ No validation errors"
echo ""
read -p "Completed? Press Enter to continue..."

# ============================================================================
# PHASE 3: UPLOAD STUDY FILE
# ============================================================================
echo ""
echo "---"
echo "PHASE 3: UPLOAD STUDY FILE"
echo "---"
echo ""
echo "1. In same expedient detail, scroll to 'Studies' section"
echo ""
echo "2. Find 'Upload Study' file drop zone"
echo ""
echo "3. Select a PDF or Image file from your computer"
echo "   (You can create a dummy file: echo 'test' > sample.txt)"
echo ""
echo "4. File should auto-upload to Firebase Storage"
echo ""
echo "Expected Result:"
echo "   ✓ File appears in Studies list"
echo "   ✓ No Firebase auth errors"
echo "   ✓ File shows upload status 'PENDING_EXTRACTION'"
echo ""
read -p "Completed? Press Enter to continue..."

# ============================================================================
# PHASE 4: VALIDATE EXPEDIENT
# ============================================================================
echo ""
echo "---"
echo "PHASE 4: VALIDATE EXPEDIENT"
echo "---"
echo ""
echo "1. Navigate to: http://localhost:3000/admin/validaciones"
echo ""
echo "2. Find the 'Juan García Pérez' expedient in the list (status 'PENDIENTE')"
echo ""
echo "3. Click to open validation panel"
echo ""
echo "4. Review displayed data:"
echo "   - Patient name and DOB"
echo "   - Vitals recorded"
echo "   - Studies uploaded"
echo ""
echo "5. Select verdict from dropdown:"
echo "   - Verdict: 'APTO' (suitable for work)"
echo "   - Status: 'APPROVED'"
echo ""
echo "6. Optionally add medical opinion in text field"
echo ""
echo "7. Click 'Validar y Firmar' button"
echo ""
echo "Expected Result:"
echo "   ✓ ValidationTask updated with status APPROVED"
echo "   ✓ Validator name recorded"
echo "   ✓ Timestamp recorded"
echo "   ✓ Expedient disappears from PENDIENTE list"
echo ""
read -p "Completed? Press Enter to continue..."

# ============================================================================
# PHASE 5: VIEW CERTIFICATE REPORT
# ============================================================================
echo ""
echo "---"
echo "PHASE 5: VIEW CERTIFICATE REPORT"
echo "---"
echo ""
echo "1. Navigate to: http://localhost:3000/admin/reportes/[expedient-id]"
echo "   (Replace [expedient-id] with the ID from Phase 1)"
echo ""
echo "2. Verify CertificateViewer displays:"
echo "   - Header: 'CERTIFICADO DE VALIDACIÓN'"
echo "   - Expedient ID"
echo "   - Validation Date"
echo "   - Patient Name: 'Juan García Pérez'"
echo "   - Patient DOB: '15/06/1985'"
echo "   - Clinic Name"
echo "   - Validator Name"
echo "   - Status: 'APPROVED' (green badge)"
echo "   - Medical Opinion (if entered)"
echo ""
echo "3. Test Print functionality:"
echo "   - Click 'Imprimir' button"
echo "   - Native browser print dialog opens"
echo "   - Select 'Print to PDF' or physical printer"
echo "   - Verify layout looks professional"
echo ""
echo "4. Test Download (future feature):"
echo "   - Click 'Descargar PDF' button"
echo "   - Should show placeholder message (feature deferred)"
echo ""
echo "Expected Result:"
echo "   ✓ Certificate displays all data correctly"
echo "   ✓ Print dialog opens without errors"
echo "   ✓ Print preview shows professional layout"
echo "   ✓ No console errors in browser DevTools"
echo ""
read -p "Completed? Press Enter to continue..."

# ============================================================================
# VERIFICATION CHECKLIST
# ============================================================================
echo ""
echo "================================================"
echo "E2E TEST VERIFICATION CHECKLIST"
echo "================================================"
echo ""
echo "Database Integration:"
echo "  [ ] Expedient created in PostgreSQL"
echo "  [ ] ValidationTask created with exam data"
echo "  [ ] Status changed from PENDIENTE → APPROVED"
echo ""
echo "API Integration:"
echo "  [ ] POST /api/expedientes - successful"
echo "  [ ] POST /api/expedientes/{id}/exam - successful"
echo "  [ ] POST /api/expedientes/{id}/studies - successful"
echo "  [ ] PUT /api/validaciones/{id} - successful"
echo "  [ ] GET /admin/reportes/{id} - successful"
echo ""
echo "Frontend UI:"
echo "  [ ] Forms submit without errors"
echo "  [ ] Data displays in all sections"
echo "  [ ] Print functionality works"
echo "  [ ] Responsive layout on desktop"
echo ""
echo "Type Safety:"
echo "  [ ] No TypeScript errors in console"
echo "  [ ] All data types match Prisma schema"
echo "  [ ] No data conversion errors"
echo ""
echo "Multi-Tenant (if testing multiple orgs):"
echo "  [ ] Expedient isolated to tenant"
echo "  [ ] Cannot view other tenant's data"
echo "  [ ] tenantId properly set in all records"
echo ""
echo ""
echo "================================================"
echo "POST-TEST SUMMARY"
echo "================================================"
echo ""
echo "If all checks passed: ✅ E2E FLOW WORKING"
echo ""
echo "If any check failed:"
echo "  1. Review error message in browser console"
echo "  2. Check PostgreSQL connection status"
echo "  3. Verify Firebase credentials loaded"
echo "  4. Check API route response in Network tab"
echo ""
echo "Next Steps for Thursday Demo:"
echo "  1. Practice this flow 2-3 times"
echo "  2. Document any UX improvements needed"
echo "  3. Prepare sample data for live demo"
echo "  4. Test on different browsers (Chrome, Firefox, Safari)"
echo ""
echo "Demo Script Example:"
echo "  'Let me show you how a company admin validates a new hire...'"
echo "  [Create expedient for demo company]"
echo "  'This is their medical file...' [Show fields]"
echo "  'Let me record their vitals...' [Add exam]"
echo "  'Upload their chest X-ray...' [Upload study]"
echo "  'Now I approve them for work...' [Validate]"
echo "  'And here's their certificate...' [Show report & print]"
echo ""
echo "Test completed!"
echo ""
