#!/bin/bash

# VERCEL DATABASE_URL VERIFICATION CHECKLIST
# ==================================================
# Use this to manually verify Vercel Settings are correct

echo "📋 VERCEL DATABASE_URL CONFIGURATION CHECKLIST"
echo "==============================================="
echo ""
echo "Follow these steps to verify DATABASE_URL is properly set:"
echo ""
echo "✅ STEP 1: Go to Vercel Dashboard"
echo "   URL: https://vercel.com/frank-saavedras-projects/web-app/settings/environment-variables"
echo ""
echo "✅ STEP 2: Look for DATABASE_URL variable"
echo "   Expected name: DATABASE_URL"
echo "   Expected value: postgresql://postgres:BQPrZrCRNzGOYzkuhaAxECtHAtVSIIzA@hopper.proxy.rlwy.net:34060/railway"
echo ""
echo "✅ STEP 3: Verify it's set for ALL environments"
echo "   ☑ Production"
echo "   ☑ Preview"
echo "   ☑ Development"
echo ""
echo "⚠️  IF DATABASE_URL IS MISSING:"
echo "   1. Click 'Add Environment Variable'"
echo "   2. Name: DATABASE_URL"
echo "   3. Value: postgresql://postgres:BQPrZrCRNzGOYzkuhaAxECtHAtVSIIzA@hopper.proxy.rlwy.net:34060/railway"
echo "   4. Select: Production, Preview, Development"
echo "   5. Click 'Save'"
echo ""
echo "🚀 AFTER ADDING/CONFIRMING:"
echo "   1. Go to: https://vercel.com/frank-saavedras-projects/web-app/deployments"
echo "   2. Find current deployment"
echo "   3. Click '...' → 'Redeploy'"
echo "   4. Wait 3-5 minutes for rebuild"
echo ""
echo "✔️  VERIFY AFTER REDEPLOY:"
echo "   Run: bash scripts/validate-vercel-connection.sh"
echo ""
echo "📊 EXPECTED OUTPUT AFTER FIX:"
echo "   ✅ /api/diagnostics: HTTP 200, hasDatabase=true"
echo "   ✅ /api/citas: HTTP 200, data=[]"
echo "   ✅ Favicon: No 404 errors"
echo ""
